strange NPE
NullPointerException: Cannot invoke "minerva.user.User.getLogin()"
because "user" is null
        at minerva.seite.WatchersService.lambda$notifyWatchers$0(WatchersService.java:36)