Expired session handling
java.lang.NullPointerException: Cannot invoke
"minerva.model.StateSO.getUser()" because the return value of
"minerva.model.StatesSO.get(github.soltaufintel.amalia.spark.Context)"
is null