Integer null check
java.lang.NullPointerException: Cannot invoke
"java.lang.Integer.intValue()" because the return value of
"java.util.Map.get(Object)" is null
	at minerva.task.TaskService.get(TaskService.java:46)
after rebuild of webapp and recall in browser